###
POST http://159.89.97.202:8080/api/getByFilter HTTP/1.1
Content-Type: application/json

{
	"query": {
		"Adi": "ahmet"
	},
	"limit": 10,
	"skip": 20
}
### 
GET http://159.89.97.202:8080 HTTP/1.1